dependencies:
  - name: PowerDNS auth
    type: github
    currentVersion: auth-4.6.0
    prefix: auth-
    repo: "PowerDNS/pdns"
    isTag: true
    issueBody: |
      Update $name from $currentVersion to $latestVersion.
      [CHANGELOG](https://doc.powerdns.com/authoritative/changelog/)
  - name: PowerDNS-Admin
    type: github
    currentVersion: v0.2.4
    prefix: v
    repo: "ngoduykhanh/PowerDNS-Admin"
    issueBody: |
      Update $name from $currentVersion to $latestVersion.
      [CHANGELOG](https://github.com/ngoduykhanh/PowerDNS-Admin/releases)
